MusicBot:
  LogLevel: DEBUG
  DiscordToken: ODA2MjI2NDczMDY5MzE0MDQ4.YBmW6g.IFwU8vxg9QMj66FWadaGzM_8bT8
  MaxAloneTime: 5m # time after the bot leaves, if it's alone in the channel
  Datastore:
    LogLevel: DEBUG
    InactiveSongTTL: 2h
    Postgres:                                                             # Postgresql database configuration
      Database: discord_bot
      User: postgres
      Password: postgres
      Host: localhost
      Port: 5432
  SlashCommands:
    Music:
      Name: music
      Description: "Life is one grand, sweet song so start the music."
    Stop:
      Name: stop
      Description: "Stop the music"
    Help:
      Name: help
      Description: "Info about using the music bot"
  Modals:
    AddSongs:
      Name: "Add Songs"
      Label: Enter names or urls of youtube songs
      Placeholder: "song name or url#1\nsong name or url#2\n..."
  Builder:
    Queue:
      Title: Music Queue
      Description: ""
      Footer: "Life is one grand, sweet song... so start the music."
      Buttons:
        Backward: "<"
        Forward: ">"
        Skip: ">>"
        Previous: "<<"
        Pause: "ll"
        Replay: "↺"
        Loop: "Loop"
        AddSongs: "Add"
        Join: "Join"
        Offline: "The bot is currently offline"
