version: '3.8'

services:
  music-bot:
    build:
      context: ..
      dockerfile: .dockerenv/Dockerfile
    container_name: music-bot
    restart: unless-stopped
    command: "-configFiles=/go/bin/conf/config.yaml -helpFiles=/go/bin/conf/README.md"
    volumes:
      - ../config.yaml:/go/bin/conf/config.yaml
      - ../README.md:/go/bin/conf/help.txt
    depends_on:
      postgres:
        condition: service_started
    networks:
      - discord-bots

  postgres:
      image: postgres:14.1-alpine
      container_name: postgres
      restart: unless-stopped
      ports:
          - 5432:5432
      environment:
          POSTGRES_DB: discord_bot
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      volumes:
          - postgres-data:/var/lib/postgresql/data
      networks:
        - discord-bots

volumes:
    postgres-data:
        driver: local
networks:
    discord-bots:
      name: discord-bots
