MusicBot:
  LogLevel: DEBUG
  DiscordToken: discord_bot_token
  SlashCommands:
    Music:
      Name: music
      Description: "Life is one grand, sweet song so start the music."
    Help:
      Name: help
      Description: "Info about using the music bot"
  Modals:
    AddSongs:
      Name: Add Songs
      Label: Enter names or urls of youtube songs
      Placeholder: "song name or url#1\nsong name or url#2\n..."
  QueueBuilder:
    Title: Music Queue
    Description: ""
    Footer: "Life is one grand, sweet song... so start the music."
    Components:
      Backward: "<"
      Forward: ">"
      Skip: ">>"
      Previous: "<<"
      Pause: "ll"
      Replay: "↺"
      Loop: "Loop"
      AddSongs: "Add"
      Join: "Join"
      Offline: "The bot is currently offline"
  Updater:
    Interval: 5s # do not set under 5s
    MaxAloneTime: 2m # time after the bot leaves, if it's alone in the channel
  Youtube:
    LogLevel: DEBUG
    MaxParallelQueries: 100
  Datastore:
    LogLevel: DEBUG

