version: '3.8'

services:
  discord-postgres:
      image: postgres:14.1-alpine
      container_name: discord-postgres
      restart: unless-stopped
      network_mode: host
      ports:
          - 5432:5432
      environment:
          POSTGRES_DB: discord_bot
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      volumes:
          - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        driver: local
