version: '3.8'

services:
  music-bot:
    build:
    # NOTE: replace 'build' with:
    #     `image: docker-hub-user/repo:imagetag`
    # When building the image with the build script and
    # pushing it to the docker-hub
      context: ..
      dockerfile: .dockerenv/Dockerfile
    container_name: music-bot
    restart: unless-stopped
    environment:
      # NOTE: these env. variables should match
      # the variables in 'postgres' service
      POSTGRES_DB: discord_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    # add the path to the config file  and the help file
    # as the command line argument when starting the bot
    command: "-configFiles=/go/bin/conf/config.yaml -helpFiles=/go/bin/conf/help.txt"
    volumes:
      # NOTE: change the '../conf/config.yaml' and '../conf/help.txt'
      # to the location of yout config.yaml file
      - ../conf/config.yaml:/go/bin/conf/config.yaml
      - ../conf/help.txt:/go/bin/conf/help.txt
    depends_on:
      postgres:
        condition: service_started
    networks:
      - discord-bots

  # the datastore service
  postgres:
      image: postgres:14.1-alpine
      container_name: postgres
      restart: unless-stopped
      ports:
          - 5432:5432
      environment:
          POSTGRES_DB: discord_bot
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      volumes:
          - postgres-data:/var/lib/postgresql/data
      networks:
        - discord-bots

volumes:
    postgres-data:
        driver: local
networks:
    discord-bots:
      name: discord-bots
