MusicBot:
  LogLevel: TRACE
  DiscordToken: discord-bot-token
  ApplicationCommands:
    Music:
      Name: music
      Description: "Life is one grand, sweet song so start the music."
    Help:
      Name: help
      Description: "Info about using the music bot"
    AddSongs:
      Name: Add songs
  QueueBuilder:
    Title: Music Queue
    Description: ""
    Footer: "Life is one grand, sweet song... so start the music."
    Components:
      Backward: "<"
      Forward: ">"
      Skip: ">>"
      Previous: "<<"
      Pause: "ll"
      Replay: "↺"
      Loop: "Loop"
      AddSongs: "Add"
  AudioPlayer:
    Channels: 2
    FrameRate: 48000
    FrameSize: 960
    Retry: 3
  Youtube:
    LogLevel: TRACE
    MaxParallelQueries: 100
  Datastore:
    LogLevel: TRACE
    Database: discord_bot
    Host: localhost
    Port: 5432
    User: postgres
    Password: postgres
