name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bring up docker stack
      run: docker-compose -f .dockerenv/docker-compose.test.yaml up -d

    - name: Test
      run: docker-compose -f .dockerenv/docker-compose.test.yaml exec -T app go test -v ./...
