name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bring up docker stack
      run: docker-compose -f .dockerenv/docker-compose.test.yaml up -d

    - name: Test
      run: docker-compose -f .dockerenv/docker-compose.test.yaml exec -T bot go test -v -p 1 ./...
