name: Go Test

on:
  # if called from other workflows
  workflow_call:
  push:

jobs:
  run_all_go_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bring up docker stack
      run: docker-compose -f .github/dockerenv/docker-compose.test.yaml up -d

    - name: Test
      run: docker-compose -f .github/dockerenv/docker-compose.test.yaml exec -T bot go test -v -p 1 ./...
