name: Publish Docker Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Go Test]
    branches:
      - main
    types:
      - completed
  push:
    tags:
      - v.**

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest tag
        id: tag
        run: |
          echo "TAG_NAME=$(git describe --tags $(git rev-list --tags='v?[0-9]+.[0-9]*' --max-count=1))" >> $GITHUB_OUTPUT
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/dockerenv/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/discord_music_bot:${{ steps.tag.outputs.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/discord_music_bot:latest
