# Publish docker image lpoto/discord_music_bot:latest
# to ghcr.io
# Run this after tests successfully complete on main
name: Publish Latest Docker image

on:
  workflow_run:
    workflows: [Go Test]
    branches:
      - main
    types:
      - completed

jobs:
  push_to_registry:
    name: Push Docker image with tag 'latest' to Docker Hub
    # make sure the tests were successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/dockerenv/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/discord_music_bot:latest

